[package]
name = "contiguous-mem"
version = "0.5.0"
edition = "2021"
description = "A contiguous memory storage"
authors = ["Tin Švagelj <tin.svagelj@live.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["memory", "contiguous", "storage", "container", "nostd"]
categories = ["data-structures", "memory-management", "no-std"]
repository = "https://github.com/Caellian/contiguous_mem"

[[example]]
name = "game_loading"
path = "examples/game_loading.rs"
required-features = ["unsafe_impl"]

[[example]]
name = "ptr_metadata"
path = "examples/ptr_metadata.rs"
required-features = ["ptr_metadata"]

[[example]]
name = "unsafe_impl"
path = "examples/unsafe_impl.rs"
required-features = ["unsafe_impl"]

[features]
default = ["unsafe_impl", "debug"]

no_std = [] # No-std support
debug = []  # Enable debug attributes

# Implementations
unsafe_impl = []

# Nightly features
ptr_metadata = []
error_in_core = []
allocator_api = []

[dev-dependencies]
byteorder = "1.4"

[package.metadata.docs.rs]
all-features = true
