name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - name: Build default
        run: cargo build --verbose
      - name: Build no_std all features
        run: cargo build --verbose --no-default-features --features no_std,debug,ptr_metadata,error_in_core
      - name: Build all features
        run: cargo build --verbose --no-default-features --features debug,ptr_metadata,error_in_core
      - name: Run tests
        run: cargo test --verbose --features ptr_metadata
