name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - name: Build default
        run: cargo build --verbose
      - name: Build no_std
        run: cargo build --verbose --no-default-features --features no_std
      - name: Build no_std with error_in_core
        run: cargo build --verbose --no-default-features --features no_std,error_in_core
      - name: Build with ptr_metadata
        run: cargo build --verbose --features ptr_metadata
      - name: Build restrictive
        run: cargo build --verbose --no-default-features --features std
      - name: Run tests
        run: cargo test --verbose --features ptr_metadata
